### ISSUE TITLE
Broken mirros

### ISSUE THREAD

**Issue by bogdanr** [taq/slackcurrent#1]
Many of the mirror don't work anymore. For example all the mirror from Romania are broken.

**Comment by taq** [comment]
I'm not updating or using this project for years. Despite the mirrors, does it still works ok?

**Comment by bogdanr** [comment]
I don't know. I only wanted the mirrors.

**Comment by taq** [comment]
So, you aren't using it and just want the list or mirrors? So, go to the Slackware page and try to get some from there.
